services:
  - type: web
    name: ecommerce-springboot-backend
    runtime: java
    rootDir: E-Commerce SpringBoot-Backend
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    plan: free