spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
  file:
    upload-dir: ${FILE_UPLOAD_DIR:/app/uploads/}

logging:
  level:
    com.ecommerce: INFO
    org.springframework: WARN
